blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: mailto:security@nexanest.com
    about: Please report security vulnerabilities via email
  - name: Documentation
    url: https://docs.nexanest.com
    about: Check our documentation for guides and tutorials
  - name: Community Support
    url: https://github.com/nexanest/nexanest/discussions
    about: Ask questions and discuss with the community