version: '3.9'

# =============================================================================
# Docker Compose Secrets Configuration
# =============================================================================
# This file defines Docker secrets for secure credential management
# Use this with: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up
# =============================================================================

secrets:
  # Database secrets
  postgres_password:
    file: ../secrets/secrets/postgres_password
  timescale_password:
    file: ../secrets/secrets/timescale_password
  redis_password:
    file: ../secrets/secrets/redis_password
  
  # Authentication secrets
  jwt_secret_key:
    file: ../secrets/secrets/jwt_secret_key
  secret_key:
    file: ../secrets/secrets/secret_key
  auth_secret_key:
    file: ../secrets/secrets/auth_secret_key
  encryption_key:
    file: ../secrets/secrets/encryption_key
  session_secret:
    file: ../secrets/secrets/session_secret
  
  # Kong secrets
  kong_password:
    file: ../secrets/secrets/kong_password
  
  # Admin secrets
  pgadmin_password:
    file: ../secrets/secrets/pgadmin_password
  first_superuser_password:
    file: ../secrets/secrets/first_superuser_password
  
  # External API keys
  openai_api_key:
    file: ../secrets/secrets/openai_api_key
  anthropic_api_key:
    file: ../secrets/secrets/anthropic_api_key
  google_client_secret:
    file: ../secrets/secrets/google_client_secret
  github_client_secret:
    file: ../secrets/secrets/github_client_secret

services:
  # PostgreSQL with secrets
  postgres:
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    # Remove hardcoded password
    environment:
      POSTGRES_DB: nexanest
      POSTGRES_USER: nexanest
      POSTGRES_MULTIPLE_DATABASES: "auth,portfolio,analytics,notifications"

  # TimescaleDB with secrets
  timescaledb:
    secrets:
      - timescale_password
    environment:
      POSTGRES_DB: timescale
      POSTGRES_USER: timescale
      POSTGRES_PASSWORD_FILE: /run/secrets/timescale_password

  # Redis with secrets
  redis:
    secrets:
      - redis_password
    command: >
      sh -c "
        REDIS_PASSWORD=$$(cat /run/secrets/redis_password)
        redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
      "

  # PgAdmin with secrets
  pgadmin:
    secrets:
      - pgadmin_password
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@nexanest.local}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password